# install file for PostgreSQL

- name: Install | Make sure dependencies are installed
  yum: name=python-psycopg2 state=present

- name: Install | Install pgtune if available (requires epel to succeed)
  yum: name=pgtune state=present
  ignore_errors: True

- name: Install postgresql db packages
  yum: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-contrib
