---
- include: access.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= 6

- include: install.yml
- include: configure.yml
- include: databases.yml
- include: users.yml
